run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign

linters-settings:
  govet:
    disable:
      - shadow

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
